<?php

/**
 * Class for adding a Business (Sub Account) in Justifi
 *
 * @link       https://bradmessenger.com/
 * @since      1.0.0
 *
 * @package    Justifi_Payments
 * @subpackage Justifi_Payments/shortcodes
 */

namespace Justifi_Payments;
use Justifi_Payments\Shortcodes\Justifi_Dashboard;

class Create_Business {
	
	public function __construct() {
		/* 
		 * Setup our AJAX hooks because the "Create My Business" button triggers an AJAX call 
		 * The action on the AJAX call is "createBiz"
		 * .../public/js/justifi-ajax.js
		 */
		add_action( 'wp_ajax_nopriv_createBiz', array( $this, 'createBiz_ajax' ));
		add_action( 'wp_ajax_createBiz', array( $this, 'createBiz_ajax' ));
	}
	
	public function business_create() {
		
		/*
		 * Setting up our arguments to get ready for our API call to Justifi
		 * The minimum requirement for creating a new Business in Justifi is a business name
		 * We go ahead and get the Business name along with a few other fields we can pass in our POST request
		 */
		$url = 'https://api.justifi.ai/v1/entities/business'; // The Justifi Create Business endpoint
		$profile_id = \Staxx\Helpers::get_organization_profile_id( $_POST['user_id'] ); // Get the Organization ID
		$business_name = sanitize_text_field( get_the_title( $profile_id ) ); // Get the Organization Title
		get_field( 'organization_contact_email', $profile_id ) ? $email = sanitize_email( get_field( 'organization_contact_email', $profile_id ) ) : $email = '';
		get_field( 'organization_contact_phone', $profile_id ) ? $phone = sanitize_text_field( get_field( 'organization_contact_phone', $profile_id ) ) : $phone = '';
		
		/* Just formatting our payload here for the POST request */
		$biz_details = array(
			"legal_name" 		=> $business_name,
			"email"				=> $email,
			"phone"				=> $phone,
		);
		
		/* 
		 * Almost all API requests to Justifi require an Access Token
		 * We've set up a helper class that can generate a token for us 
		 * @class-justifi-helpers.php 
		 */
		$access_token = Justifi_Helpers::get_access_token();
			
		/* 
		 * Make our API call (POST request), passing the required headers and payload
		 * Set the response to a variable at the same time
		 */
		$response = wp_remote_post( $url, array(
			'headers' => array(
				'Content-Type' => 'application/json',
				'Authorization' => 'Bearer ' . $access_token,
			),
			'body' => wp_json_encode( $biz_details ),
		) );
		
		/* Error handling */
		if ( is_wp_error( $response ) ) {
			return false;
		}
		
		/* The response is returned in JSON so we need to do some cleanup */
		$response_body = wp_remote_retrieve_body( $response );
		$decoded = json_decode($response_body, true);
		$decoded['id'] ? $business_id = $decoded['id'] : $business_id = '';
		
		/* 
		 * Check to see if that Business has already been created 
		 * If everything is good the account has been created and 
		 * we should receive a few things back in the response, including a 
		 * Business ID generated by Justifi
		 */
		if ( !empty( $decoded['error']['code'] ) && $decoded['error']['code'] == 'name_already_taken' ) {
			
			$html = '<div class="message error-duplicate" style="padding:15px">
						<p>It looks like that name is already taken within Justifi.</p>
						<p>Try <a href="https://staging.justifi.com/dashboard/edit-profile/">editing your prifile</a> and updating your main title to something unique.</p>
					</div>';
			
			echo wp_json_encode( $html ); 
			
		} else if (  $profile_id && $business_id ) {
			
			/* Update the post_meta box for the Organization and add the new Business ID */
			$upm = update_post_meta( $profile_id, 'justifi_business_id', $business_id );
			
			/* Reload the Dashboard */
			ob_start();
			//require Justifi_Payments_FILE_PATH . 'includes/templates/dashboard/dashboard-before.php';  // Before Wrapper
			$output = ob_get_clean();
			
			$dashboard = new Justifi_Dashboard();
			$output .= $dashboard->justifi_connect( $business_id ); // Business Status
			//$output .= $dashboard->justifi_onboarding( $business_id ); // Onboarding Status
			//$output .= $dashboard->justifi_business_form( $business_id ); // Business Form Status
			$output .= $dashboard->justifi_payment_provision_form( $business_id );
			
			ob_start();
			//require Justifi_Payments_FILE_PATH . 'includes/templates/dashboard/dashboard-after.php'; // After Wrapper
			$output .= ob_get_clean();
			
			echo wp_json_encode( $output ); 
			
		} else {
			$html = '<div class="message create-error" style="padding:15px">
						<p>There was an issue setting up your Account.  Please contact support.</p>
					</div>';
			echo wp_json_encode( $html ); 
		}
		
		/* Always make sure we kill an AJAX request when we know where done */
		wp_die();
		
	}
	
	/* Our hook Callback to start everything off */
	function createBiz_ajax() {
		
		if ( current_user_can( 'edit_posts' ) && isset( $_POST['nonce'] ) &&  wp_verify_nonce( $_POST['nonce'], 'activate-and-connect' ) ) {
			
			$this->business_create();
		
		}  else {
			 die ( 'I see what\'s happening here.');
		 }
		 
		
	}
}

new \Justifi_Payments\Create_Business();